using System;
using System.IO;
using System.Text;
using Il2Cpp;
using Il2CppInterop.Runtime;
using MelonLoader;
using UnityEngine;

namespace LiarsBarMod.Features.Dev
{
    public static class StateDumper
    {
        public static string GetDumpFilePath()
        {
            try
            {
                string desktopPath = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
                if (!string.IsNullOrEmpty(desktopPath) && Directory.Exists(desktopPath))
                {
                    return Path.Combine(desktopPath, "liarsbar_dump.txt");
                }
            }
            catch { }

            string baseDir = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "UserData");
            if (!Directory.Exists(baseDir)) Directory.CreateDirectory(baseDir);
            return Path.Combine(baseDir, "liarsbar_dump.txt");
        }

        public static string DumpStateToDesktop(string gameTypeStr, Manager mgr, GameObject me, GameObject[] players)
        {
            try
            {
                string filePath = GetDumpFilePath();
                StringBuilder sb = new StringBuilder();

                sb.AppendLine("=================================================================");
                sb.AppendLine("      LIAR'S BAR - Live Game State & Symbol Inspection Dump");
                sb.AppendLine("      Generated by Inkwell's Liar's Bar Menu v4.4");
                sb.AppendLine($"      Timestamp: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
                sb.AppendLine("=================================================================");
                sb.AppendLine();

                sb.AppendLine("------------------ MATCH & SESSION TELEMETRY ------------------");
                sb.AppendLine($"[+] Active Game Mode: {gameTypeStr}");
                if (mgr != null)
                {
                    sb.AppendLine($"[+] Manager Instance: ACTIVE | GameStarted: {mgr.GameStarted}");
                    sb.AppendLine($"[+] Active Player Slot: {mgr.NetworkActivePlayerSlot}");
                    sb.AppendLine($"[+] Total Players Registered: {(mgr.Players != null ? mgr.Players.Count : 0)}");
                }
                else
                {
                    sb.AppendLine("[-] Manager Instance: NULL (In Main Menu / Lobby Scene)");
                }

                sb.AppendLine();
                sb.AppendLine("------------------ ACTIVE MANAGERS STATUS ------------------");
                var deckMgr = UnityEngine.Object.FindFirstObjectByType<DeckGamePlayManager>();
                var chaosDeckMgr = UnityEngine.Object.FindFirstObjectByType<ChaosDeckGamePlayManager>();
                var diceMgr = UnityEngine.Object.FindFirstObjectByType<DiceGamePlayManager>();
                var pokerMgr = UnityEngine.Object.FindFirstObjectByType<PokerGamePlayManager>();
                var texasMgr = UnityEngine.Object.FindFirstObjectByType<TexasGamePlayManager>();
                var spinMgr = UnityEngine.Object.FindFirstObjectByType<LiarsSpinGameplayManager>();
                var roulMgr = UnityEngine.Object.FindFirstObjectByType<RouletteGameManager>();
                var blorfMgr = UnityEngine.Object.FindFirstObjectByType<BlorfGamePlayManager>();
                var blorfMMMgr = UnityEngine.Object.FindFirstObjectByType<BlorfMatchMakingGamePlayManager>();
                var dbMgr = DatabaseManager.instance;

                sb.AppendLine($"[+] DeckGamePlayManager: {(deckMgr != null ? "ACTIVE" : "null")}");
                if (deckMgr != null) sb.AppendLine($"    CardsOnTable: {deckMgr.CardsOnTable} | RoundCard: {deckMgr.RoundCard} | DeckMode: {deckMgr.DeckMode}");
                sb.AppendLine($"[+] ChaosDeckGamePlayManager: {(chaosDeckMgr != null ? "ACTIVE" : "null")}");
                if (chaosDeckMgr != null) sb.AppendLine($"    CardsOnTable: {chaosDeckMgr.CardsOnTable} | RoundCard: {chaosDeckMgr.RoundCard}");
                sb.AppendLine($"[+] DiceGamePlayManager: {(diceMgr != null ? "ACTIVE" : "null")}");
                if (diceMgr != null) sb.AppendLine($"    DiceMode: {diceMgr.NetworkDiceMode} | LastDice: {diceMgr.NetworkLastDice} | LastCount: {diceMgr.NetworkLastCount} | TotalCount: {diceMgr.NetworkTotalCount}");
                sb.AppendLine($"[+] PokerGamePlayManager: {(pokerMgr != null ? "ACTIVE" : "null")}");
                sb.AppendLine($"[+] TexasGamePlayManager: {(texasMgr != null ? "ACTIVE" : "null")}");
                if (texasMgr != null)
                {
                    var openList = new System.Collections.Generic.List<int>();
                    if (texasMgr.OpenTableCards != null)
                    {
                        for (int i = 0; i < texasMgr.OpenTableCards.Count; i++) openList.Add(texasMgr.OpenTableCards[i]);
                    }
                    string openStr = openList.Count > 0 ? string.Join(",", openList) : "none";

                    var allList = new System.Collections.Generic.List<int>();
                    if (texasMgr.AllTableCards != null)
                    {
                        for (int i = 0; i < texasMgr.AllTableCards.Count; i++) allList.Add(texasMgr.AllTableCards[i]);
                    }
                    string allStr = allList.Count > 0 ? string.Join(",", allList) : "none";
                    sb.AppendLine($"    OpenTableCards: [{openStr}] | AllTableCards: [{allStr}]");
                }
                sb.AppendLine($"[+] LiarsSpinGameplayManager: {(spinMgr != null ? "ACTIVE" : "null")}");
                sb.AppendLine($"[+] RouletteGameManager: {(roulMgr != null ? "ACTIVE" : "null")}");
                sb.AppendLine($"[+] BlorfGamePlayManager: {(blorfMgr != null ? "ACTIVE" : "null")}");
                sb.AppendLine($"[+] BlorfMatchMakingGamePlayManager: {(blorfMMMgr != null ? "ACTIVE" : "null")}");
                sb.AppendLine($"[+] DatabaseManager: {(dbMgr != null ? "ACTIVE" : "null")}");

                // Lobby Slots & Controllers Inspection
                try
                {
                    var allSlots = UnityEngine.Object.FindObjectsOfType<LobbySlot>();
                    if (allSlots != null && allSlots.Length > 0)
                    {
                        sb.AppendLine();
                        sb.AppendLine($"------------------ LOBBY SLOTS INSPECTION ({allSlots.Length} slots) ------------------");
                        for (int sIdx = 0; sIdx < allSlots.Length; sIdx++)
                        {
                            var s = allSlots[sIdx];
                            if (s == null) continue;
                            string txt = s.NameText != null ? s.NameText.text : "null";
                            bool hasChar = s.SelectChar != null && s.SelectChar.activeInHierarchy;
                            sb.AppendLine($"  [Slot {sIdx}] Name: '{s.name}' | Dolu: {s.Dolu} | NetDolu: {s.NetworkDolu} | HasChar: {hasChar}");
                            sb.AppendLine($"          PlayerName: '{s.PlayerName}' | NetPlayerName: '{s.NetworkPlayerName}' | Text: '{txt}'");
                        }
                    }
                }
                catch { }

                sb.AppendLine();
                sb.AppendLine("------------------ ACTIVE PLAYERS ROSTER ------------------");
                if (players == null || players.Length == 0)
                {
                    try
                    {
                        var allStats = UnityEngine.Object.FindObjectsOfType<PlayerStats>();
                        if (allStats != null && allStats.Length > 0)
                        {
                            var pList = new System.Collections.Generic.List<GameObject>();
                            for (int i = 0; i < allStats.Length; i++)
                            {
                                if (allStats[i] != null && allStats[i].gameObject != null) pList.Add(allStats[i].gameObject);
                            }
                            players = pList.ToArray();
                        }
                    }
                    catch { }
                }

                if (players != null && players.Length > 0)
                {
                    sb.AppendLine($"[+] Discovered {players.Length} player entities:");
                    for (int i = 0; i < players.Length; i++)
                    {
                        var p = players[i];
                        if (p == null) { sb.AppendLine($"  [{i + 1}] NULL GAMEOBJECT"); continue; }

                        bool isMe = p == me;
                        var ps = p.GetComponent<PlayerStats>();
                        var poc = p.GetComponent<PlayerObjectController>();
                        string pName = ps != null ? ps.NetworkPlayerName : p.name;
                        ulong steamId = poc != null ? poc.PlayerSteamID : 0;
                        int connId = poc != null ? poc.ConnectionID : -1;
                        bool dead = ps != null && ps.NetworkDead;
                        int slot = ps != null ? ps.Slot : -1;

                        sb.AppendLine($"  [{i + 1}] Player: '{pName}' {(isMe ? "[YOU]" : "")} | Slot: {slot} | Dead: {dead}");
                        sb.AppendLine($"       SteamID: {steamId} | ConnID: {connId} | WorldPos: {p.transform.position}");

                        // Revolver details
                        try
                        {
                            var dk = p.GetComponent<DeckGameplay>();
                            var cd = p.GetComponent<ChaosDeckGameplay>();
                            var bg = p.GetComponent<BlorfGamePlay>();
                            var bmm = p.GetComponent<BlorfGamePlayMatchMaking>();
                            var cg = p.GetComponent<ChaosGamePlay>();
                            if (dk != null) sb.AppendLine($"       Deck Revolver: Bullet={dk.NetworkrevolverBullet} Current={dk.NetworkcurrentRevolver}");
                            if (cd != null) sb.AppendLine($"       ChaosDeck Revolver: Bullet={cd.Networkrevolverbulllet} Current={cd.Networkcurrentrevoler}");
                            if (bg != null) sb.AppendLine($"       Blorf Revolver: Bullet={bg.Networkrevolverbulllet} Current={bg.Networkcurrentrevoler}");
                            if (bmm != null) sb.AppendLine($"       BlorfMM Revolver: Bullet={bmm.Networkrevolverbulllet} Current={bmm.Networkcurrentrevoler}");
                            if (cg != null) sb.AppendLine($"       Chaos Revolver: Bullet={cg.Networkrevolverbulllet} Current={cg.Networkcurrentrevoler}");
                        }
                        catch { }

                        // Dice details
                        try
                        {
                            var dg = p.GetComponent<DiceGamePlay>();
                            if (dg != null)
                            {
                                string diceSyncStr = (dg.DiceValues != null && dg.DiceValues.Count > 0)
                                    ? string.Join(",", new System.Collections.Generic.List<int>(dg.DiceValues.ToArray()))
                                    : "empty";
                                
                                var renderFaces = new System.Collections.Generic.List<int>();
                                if (dg.dicerenders != null)
                                {
                                    for (int di = 0; di < dg.dicerenders.Count; di++)
                                    {
                                        var d = dg.dicerenders[di];
                                        if (d != null) renderFaces.Add(d.Face);
                                    }
                                }
                                string renderStr = renderFaces.Count > 0 ? string.Join(",", renderFaces) : "none";
                                sb.AppendLine($"       DiceGamePlay: SyncDice=[{diceSyncStr}] | RenderFaces=[{renderStr}] | DrinkCount={dg.NetworkdrinkCount} | Looking={dg.NetworkLooking}");
                            }
                        }
                        catch { }

                        // Poker details
                        try
                        {
                            var pg = p.GetComponent<PokerGamePlay>();
                            if (pg != null)
                            {
                                var bList = new System.Collections.Generic.List<int>();
                                if (pg.fullbullets != null)
                                {
                                    for (int bi = 0; bi < pg.fullbullets.Count; bi++) bList.Add(pg.fullbullets[bi]);
                                }
                                string bulletStr = bList.Count > 0 ? string.Join(",", bList) : "none";
                                string cardTypesStr = pg.CardTypes != null ? string.Join(",", new System.Collections.Generic.List<int>(pg.CardTypes.ToArray())) : "none";
                                int cardCount = pg.Cards != null ? pg.Cards.Count : 0;
                                sb.AppendLine($"       PokerGamePlay: CardTypes=[{cardTypesStr}] | CardsCount={cardCount} | FullBullets=[{bulletStr}] | CardVal={pg.NetworkCardValue}");
                            }
                        }
                        catch { }

                        // Texas details
                        try
                        {
                            var tg = p.GetComponent<TexasGamePlay>();
                            if (tg != null)
                            {
                                string cardTypesStr = tg.CardTypes != null ? string.Join(",", new System.Collections.Generic.List<int>(tg.CardTypes.ToArray())) : "none";
                                sb.AppendLine($"       TexasGamePlay: Bullets={tg.NetworkBullets} | Folded={tg.NetworkFolded} | Hand=[{cardTypesStr}]");
                            }
                        }
                        catch { }

                        // Spin details
                        try
                        {
                            var sg = p.GetComponent<SpinGamePlay>();
                            if (sg != null)
                            {
                                sb.AppendLine($"       SpinGamePlay: ServerSlots=({sg._srvS1},{sg._srvS2},{sg._srvS3},{sg._srvS4}) | LocalSlots=({sg._localSlot1},{sg._localSlot2},{sg._localSlot3},{sg._localSlot4}) | Bet={sg.BetCount}");
                            }
                        }
                        catch { }
                    }
                }
                else
                {
                    sb.AppendLine("[-] No active players in session.");
                }

                sb.AppendLine();
                sb.AppendLine("------------------ LIVE IL2CPP TYPE & METHOD REFLECTION ------------------");
                DumpTypeSymbols<Card>(sb, "Card");
                DumpTypeSymbols<PokerCard>(sb, "PokerCard");
                DumpTypeSymbols<TexasCard>(sb, "TexasCard");
                DumpTypeSymbols<Il2Cpp.Dice>(sb, "Dice");
                DumpTypeSymbols<DiceGamePlay>(sb, "DiceGamePlay");
                DumpTypeSymbols<DiceGamePlayManager>(sb, "DiceGamePlayManager");
                DumpTypeSymbols<PokerGamePlay>(sb, "PokerGamePlay");
                DumpTypeSymbols<PokerGamePlayManager>(sb, "PokerGamePlayManager");
                DumpTypeSymbols<TexasGamePlay>(sb, "TexasGamePlay");
                DumpTypeSymbols<TexasGamePlayManager>(sb, "TexasGamePlayManager");
                DumpTypeSymbols<DeckGameplay>(sb, "DeckGameplay");
                DumpTypeSymbols<ChaosDeckGameplay>(sb, "ChaosDeckGameplay");
                DumpTypeSymbols<BlorfGamePlay>(sb, "BlorfGamePlay");
                DumpTypeSymbols<SpinGamePlay>(sb, "SpinGamePlay");
                DumpTypeSymbols<RouletteGamePlay>(sb, "RouletteGamePlay");
                DumpTypeSymbols<Manager>(sb, "Manager");
                DumpTypeSymbols<PlayerObjectController>(sb, "PlayerObjectController");
                DumpTypeSymbols<PlayerStats>(sb, "PlayerStats");
                DumpTypeSymbols<LobbySlot>(sb, "LobbySlot");
                DumpTypeSymbols<SteamLobby>(sb, "SteamLobby");

                File.WriteAllText(filePath, sb.ToString());
                MelonLogger.Msg($"[+] Successfully dumped game state to: {filePath}");
                return filePath;
            }
            catch (Exception ex)
            {
                MelonLogger.Error($"[-] Failed to dump game state: {ex.Message}");
                return $"Error: {ex.Message}";
            }
        }

        private static void DumpTypeSymbols<T>(StringBuilder sb, string friendlyName)
        {
            try
            {
                var il2cppType = Il2CppType.Of<T>();
                if (il2cppType == null)
                {
                    sb.AppendLine($"[-] Type {friendlyName} not found in Il2Cpp domain.");
                    return;
                }

                sb.AppendLine($"\n=== IL2CPP Type: {il2cppType.FullName} (Base: {il2cppType.BaseType?.Name}) ===");

                // Fields
                try
                {
                    var fields = il2cppType.GetFields(Il2CppSystem.Reflection.BindingFlags.Public | Il2CppSystem.Reflection.BindingFlags.NonPublic | Il2CppSystem.Reflection.BindingFlags.Instance | Il2CppSystem.Reflection.BindingFlags.Static);
                    sb.AppendLine($"  --- Fields ({fields.Length}) ---");
                    foreach (var f in fields)
                    {
                        if (f.Name.StartsWith("Native")) continue;
                        sb.AppendLine($"    [F] {f.FieldType.Name} {f.Name}");
                    }
                }
                catch { }

                // Properties
                try
                {
                    var props = il2cppType.GetProperties(Il2CppSystem.Reflection.BindingFlags.Public | Il2CppSystem.Reflection.BindingFlags.NonPublic | Il2CppSystem.Reflection.BindingFlags.Instance);
                    sb.AppendLine($"  --- Properties ({props.Length}) ---");
                    foreach (var p in props)
                    {
                        if (p.Name.StartsWith("Native")) continue;
                        sb.AppendLine($"    [P] {p.PropertyType.Name} {p.Name}");
                    }
                }
                catch { }

                // Methods
                try
                {
                    var methods = il2cppType.GetMethods(Il2CppSystem.Reflection.BindingFlags.Public | Il2CppSystem.Reflection.BindingFlags.NonPublic | Il2CppSystem.Reflection.BindingFlags.Instance | Il2CppSystem.Reflection.BindingFlags.Static);
                    sb.AppendLine($"  --- Methods ({methods.Length}) ---");
                    foreach (var m in methods)
                    {
                        if (m.Name.StartsWith("Native") || m.Name.StartsWith("get_") || m.Name.StartsWith("set_")) continue;
                        try
                        {
                            var pars = m.GetParameters();
                            string pstr = "";
                            if (pars != null)
                            {
                                for (int i = 0; i < pars.Length; i++)
                                    pstr += (i > 0 ? ", " : "") + pars[i].ParameterType.Name + " " + pars[i].Name;
                            }
                            sb.AppendLine($"    [M] {m.ReturnType.Name} {m.Name}({pstr})");
                        }
                        catch
                        {
                            sb.AppendLine($"    [M] {m.Name}");
                        }
                    }
                }
                catch { }
            }
            catch (Exception ex)
            {
                sb.AppendLine($"[-] Reflection error on {friendlyName}: {ex.Message}");
            }
        }
    }
}
